test_env:
  base_url: http://192.168.2.253:9998
  account:
    username: 18228890788
    password: MeJItNw2ZoAgo2qLM2MaXA
  mysql:
    host: 192.168.2.253
    account: test
    pwd: 123456
    dbname: cloud_account_system
  redis:
    host: 192.168.2.253
    port: 6379
    pwd: 123456
h5_test:
  # h5测试环境
  base_url: http://192.168.2.253:9998
  account:
      unionId: ojIr21Tj0-YWFNtqOoBvIsspKQ3c
      pkManagerCorp: a18984a3636b4e4186e5  # type=0传商户pk，type=1传群组pk
      type: 0 # 当前类型0--商户，1--群组
  group_account:
    unionId: ojIr21Tj0-YWFNtqOoBvIsspKQ3c
    pkManagerCorp: 592c6dbd-f6a1-4873-bc1f-cc92887f581e  # type=0传商户pk，type=1传群组pk
    type: 1 # 当前类型0--商户，1--群组
h5_pro:
  # h5线上环境
  base_url: https://www.joolgo.com:9998
  account:
    unionId:
    pkManagerCorp:
    type:
pro_env:
  base_url: https://www.joolgo.com:9998
  account:
    username: 17611111111
    password: 8ICHetKU4lK1QWEKjY1+TQ==
  mysql:
    host: 123
    account: wksql01
    pwd: 123
    dbname: cloud_account_system
  redis:
    host: 192.168.2.253
    port: 6379
    pwd: 123456
