test_env:
  base_url: http://192.168.2.253:9998
  account:
    username: 18228890788
    password: MeJItNw2ZoAgo2qLM2MaXA
  mysql:
    host: 192.168.2.253
    account: test
    pwd: 123456
    dbname: cloud_account_system
  redis:
    host: 192.168.2.253
    port: 6379
    pwd: 123456

pro_env:
  base_url: https://www.joolgo.com:9998
  account:
    username: 17611111111
    password: 8ICHetKU4lK1QWEKjY1+TQ==
  mysql:
    host: 123
    account: wksql01
    pwd: 123
    dbname: cloud_account_system
  redis:
    host: 192.168.2.253
    port: 6379
    pwd: 123456
